// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP4Zjkc0x3F41tO-oJFGWV6Jc0jYXiugE',
    appId: '1:657625010643:web:c9c25a2cebfc6f46fb9f26',
    messagingSenderId: '657625010643',
    projectId: 'flutter-firebase-7a330',
    authDomain: 'flutter-firebase-7a330.firebaseapp.com',
    storageBucket: 'flutter-firebase-7a330.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wexQsK4J-Sn0bsP70w-bsgD22xfgslQ',
    appId: '1:657625010643:android:6914ef79368da9dffb9f26',
    messagingSenderId: '657625010643',
    projectId: 'flutter-firebase-7a330',
    storageBucket: 'flutter-firebase-7a330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOdMxipmWUsVh4cxYTwMr-7jOlc8QHiY',
    appId: '1:657625010643:ios:f0243c09b75845aefb9f26',
    messagingSenderId: '657625010643',
    projectId: 'flutter-firebase-7a330',
    storageBucket: 'flutter-firebase-7a330.appspot.com',
    iosClientId: '657625010643-su9vlg2q27osogvkr7j2k89858to16tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOdMxipmWUsVh4cxYTwMr-7jOlc8QHiY',
    appId: '1:657625010643:ios:01d13001d42abdfdfb9f26',
    messagingSenderId: '657625010643',
    projectId: 'flutter-firebase-7a330',
    storageBucket: 'flutter-firebase-7a330.appspot.com',
    iosClientId: '657625010643-c27j94jvjte4qoaslgcuk7p6h387e28c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
